"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 23:57:07.207536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cal_dias',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('fecha', 'tipo')
    )
    op.create_table('cal_suspensiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desde', sa.Date(), nullable=False),
    sa.Column('hasta', sa.Date(), nullable=False),
    sa.Column('motivo', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('valor', sa.String(length=200), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo', 'valor')
    )
    with op.batch_alter_table('catalogos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalogos_tipo'), ['tipo'], unique=False)

    op.create_table('config',
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('binario', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('festivos',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('fecha')
    )
    op.create_table('firmantes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('cargo', sa.String(length=120), nullable=False),
    sa.Column('firma', sa.LargeBinary(), nullable=True),
    sa.Column('firma_mime', sa.String(length=40), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantillas',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('es_sistema', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('rutas',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terminos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('dias', sa.Integer(), nullable=False),
    sa.Column('habil', sa.Boolean(), nullable=False),
    sa.Column('responsable', sa.String(length=80), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('rol_permisos',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rol_id', 'permiso')
    )
    op.create_table('ruta_pasos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruta_id', sa.String(length=32), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('materia', sa.String(length=120), nullable=False),
    sa.Column('origen', sa.String(length=60), nullable=False),
    sa.Column('termino', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ruta_pasos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ruta_pasos_ruta_id'), ['ruta_id'], unique=False)

    op.create_table('tipo_ruta',
    sa.Column('tipo_solicitud', sa.String(length=160), nullable=False),
    sa.Column('ruta_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tipo_solicitud')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=60), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('preferencias', sa.JSON(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nombre', sa.String(length=160), nullable=False),
    sa.Column('entidad', sa.String(length=40), nullable=False),
    sa.Column('entidad_id', sa.String(length=64), nullable=False),
    sa.Column('accion', sa.String(length=20), nullable=False),
    sa.Column('antes', sa.JSON(), nullable=True),
    sa.Column('despues', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_entidad'), ['entidad'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_fecha'), ['fecha'], unique=False)

    op.create_table('procesos',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('radicado', sa.String(length=60), nullable=False),
    sa.Column('naturaleza', sa.String(length=40), nullable=False),
    sa.Column('clase', sa.String(length=200), nullable=False),
    sa.Column('demandante', sa.String(length=300), nullable=False),
    sa.Column('demandado', sa.String(length=300), nullable=False),
    sa.Column('fecha_rad', sa.Date(), nullable=True),
    sa.Column('situacion', sa.String(length=40), nullable=False),
    sa.Column('macroetapa', sa.String(length=120), nullable=False),
    sa.Column('notas', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procesos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procesos_radicado'), ['radicado'], unique=False)

    op.create_table('sesiones',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('sesiones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sesiones_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('actuaciones',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('proceso_id', sa.String(length=32), nullable=False),
    sa.Column('cuaderno', sa.String(length=120), nullable=False),
    sa.Column('materia', sa.String(length=120), nullable=False),
    sa.Column('tipo_solicitud', sa.String(length=160), nullable=False),
    sa.Column('origen', sa.String(length=60), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_memorial', sa.Date(), nullable=True),
    sa.Column('constancia', sa.Date(), nullable=True),
    sa.Column('pasa', sa.String(length=40), nullable=False),
    sa.Column('pase', sa.Date(), nullable=True),
    sa.Column('providencia', sa.Date(), nullable=True),
    sa.Column('ejecutoria', sa.Date(), nullable=True),
    sa.Column('cumplida', sa.Date(), nullable=True),
    sa.Column('termino', sa.String(length=200), nullable=False),
    sa.Column('termino_dias', sa.Integer(), nullable=True),
    sa.Column('termino_habil', sa.Boolean(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('suspende', sa.Boolean(), nullable=False),
    sa.Column('obs', sa.Text(), nullable=False),
    sa.Column('ruta_id', sa.String(length=32), nullable=False),
    sa.Column('paso_idx', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proceso_id'], ['procesos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actuaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actuaciones_proceso_id'), ['proceso_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actuaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actuaciones_proceso_id'))

    op.drop_table('actuaciones')
    with op.batch_alter_table('sesiones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sesiones_usuario_id'))

    op.drop_table('sesiones')
    with op.batch_alter_table('procesos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procesos_radicado'))

    op.drop_table('procesos')
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_fecha'))
        batch_op.drop_index(batch_op.f('ix_auditoria_entidad'))

    op.drop_table('auditoria')
    op.drop_table('usuarios')
    op.drop_table('tipo_ruta')
    with op.batch_alter_table('ruta_pasos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ruta_pasos_ruta_id'))

    op.drop_table('ruta_pasos')
    op.drop_table('rol_permisos')
    op.drop_table('terminos')
    op.drop_table('rutas')
    op.drop_table('roles')
    op.drop_table('plantillas')
    op.drop_table('firmantes')
    op.drop_table('festivos')
    op.drop_table('config')
    with op.batch_alter_table('catalogos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalogos_tipo'))

    op.drop_table('catalogos')
    op.drop_table('cal_suspensiones')
    op.drop_table('cal_dias')
    # ### end Alembic commands ###
