"""v2: penal, constitucionales, audiencias, SIERJU y personal

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-09 21:56:35.795721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('cargo', sa.String(length=120), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proceso_solicitudes_penales',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('proceso_id', sa.String(length=32), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=300), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('entrada', sa.String(length=60), nullable=False),
    sa.Column('salida', sa.String(length=60), nullable=False),
    sa.Column('fecha_salida', sa.Date(), nullable=True),
    sa.Column('hora_salida', sa.String(length=5), nullable=False),
    sa.Column('detalle_salida', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['proceso_id'], ['procesos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proceso_solicitudes_penales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proceso_solicitudes_penales_proceso_id'), ['proceso_id'], unique=False)

    op.create_table('stat_eventos',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('seccion', sa.String(length=20), nullable=False),
    sa.Column('fila', sa.Text(), nullable=False),
    sa.Column('columna', sa.Text(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('proceso_id', sa.String(length=32), nullable=True),
    sa.Column('nota', sa.Text(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proceso_id'], ['procesos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stat_eventos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stat_eventos_fecha'), ['fecha'], unique=False)

    # add_column directo (no batch): recrear procesos con foreign_keys=ON borraría en cascada sus actuaciones
    op.add_column('actuaciones', sa.Column('tp_tipo', sa.String(length=120), nullable=False, server_default=''))
    op.add_column('actuaciones', sa.Column('asignado_a', sa.String(length=200), nullable=False, server_default=''))
    op.add_column('actuaciones', sa.Column('tipo_providencia', sa.String(length=40), nullable=False, server_default=''))
    op.add_column('actuaciones', sa.Column('modo_cierre', sa.String(length=40), nullable=False, server_default=''))
    op.add_column('actuaciones', sa.Column('salida_stat', sa.String(length=200), nullable=False, server_default=''))
    op.add_column('actuaciones', sa.Column('entrada_stat', sa.String(length=200), nullable=False, server_default=''))
    op.add_column('actuaciones', sa.Column('es_audiencia', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('actuaciones', sa.Column('aud_fecha', sa.Date(), nullable=True))
    op.add_column('actuaciones', sa.Column('aud_hora', sa.String(length=5), nullable=False, server_default=''))
    op.add_column('actuaciones', sa.Column('aud_estado', sa.String(length=40), nullable=False, server_default=''))
    op.add_column('actuaciones', sa.Column('aud_tipo', sa.String(length=200), nullable=False, server_default=''))
    op.add_column('actuaciones', sa.Column('aud_causa', sa.String(length=300), nullable=False, server_default=''))
    op.add_column('actuaciones', sa.Column('aud_inmediata', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('actuaciones', sa.Column('cancelacion_de', sa.String(length=32), nullable=False, server_default=''))
    op.add_column('actuaciones', sa.Column('recurso_tipo', sa.String(length=40), nullable=False, server_default=''))
    op.add_column('actuaciones', sa.Column('recurso_fecha', sa.Date(), nullable=True))
    op.add_column('actuaciones', sa.Column('recurso_objeto', sa.String(length=20), nullable=False, server_default=''))
    op.add_column('actuaciones', sa.Column('rec_traslado', sa.Date(), nullable=True))
    op.add_column('actuaciones', sa.Column('superior_resultado', sa.String(length=200), nullable=False, server_default=''))
    op.add_column('actuaciones', sa.Column('superior_fecha', sa.Date(), nullable=True))
    op.add_column('actuaciones', sa.Column('rec_impug', sa.String(length=5), nullable=False, server_default=''))
    op.add_column('actuaciones', sa.Column('rec_impug_result', sa.String(length=200), nullable=False, server_default=''))
    op.add_column('actuaciones', sa.Column('rec_impug_fecha', sa.Date(), nullable=True))
    op.add_column('actuaciones', sa.Column('remate_realizado', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('actuaciones', sa.Column('amparo_pobreza_concedido', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('actuaciones', sa.Column('notif_fecha', sa.Date(), nullable=True))
    op.add_column('actuaciones', sa.Column('notif_forma', sa.String(length=40), nullable=False, server_default=''))
    op.add_column('actuaciones', sa.Column('ejec_dias', sa.Integer(), nullable=False, server_default='3'))
    op.add_column('procesos', sa.Column('tipo_sierju', sa.String(length=300), nullable=False, server_default=''))
    op.add_column('procesos', sa.Column('via', sa.String(length=20), nullable=False, server_default='Oral'))
    op.add_column('procesos', sa.Column('tipo_entrada', sa.String(length=200), nullable=False, server_default=''))
    op.add_column('procesos', sa.Column('fecha_terminacion', sa.Date(), nullable=True))
    op.add_column('procesos', sa.Column('fecha_archivo', sa.Date(), nullable=True))
    op.add_column('procesos', sa.Column('forma_salida', sa.String(length=200), nullable=False, server_default=''))
    op.add_column('procesos', sa.Column('tramite_posterior', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('procesos', sa.Column('fecha_tramite_posterior', sa.Date(), nullable=True))
    op.add_column('procesos', sa.Column('noticia_criminal', sa.String(length=60), nullable=False, server_default=''))
    op.add_column('procesos', sa.Column('solicitud_penal', sa.String(length=300), nullable=False, server_default=''))
    op.add_column('procesos', sa.Column('delitos_adicionales', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('procesos', sa.Column('impugnacion', sa.String(length=10), nullable=False, server_default=''))
    op.add_column('procesos', sa.Column('fecha_impugnacion', sa.Date(), nullable=True))
    op.add_column('procesos', sa.Column('decision_2da', sa.String(length=200), nullable=False, server_default=''))
    op.add_column('procesos', sa.Column('medida_tutela', sa.String(length=10), nullable=False, server_default=''))
    op.add_column('procesos', sa.Column('des_tutela', sa.String(length=60), nullable=False, server_default=''))
    op.add_column('procesos', sa.Column('des_req', sa.Date(), nullable=True))
    op.add_column('procesos', sa.Column('des_apertura', sa.String(length=40), nullable=False, server_default=''))
    op.add_column('procesos', sa.Column('des_consulta', sa.String(length=40), nullable=False, server_default=''))
    op.add_column('procesos', sa.Column('cuaderno_inicial', sa.String(length=120), nullable=False, server_default='Principal'))
    op.add_column('procesos', sa.Column('cuadernos', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('ruta_pasos', sa.Column('es_audiencia', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('ruta_pasos', sa.Column('aud_estado', sa.String(length=40), nullable=False, server_default=''))

    _datos()
    # ### end Alembic commands ###


# Copia congelada de lo que agregó la v2 del HTML. En una BD nueva estas tablas están vacías y
# las llena sembrar() desde catalogos.json; aquí solo se completa una BD ya sembrada, sin duplicar.
_GARANTIAS = (
    'r_garantias',
    'Control de garantías: radicación → auto fija audiencia → audiencia / salida anticipada',
    'Una radicación puede contener varias solicitudes. Cada solicitud puede resolverse en audiencia '
    'o terminar antes por remisión, retiro u otra salida no efectiva',
    [
        ('Radicación y pase al despacho', 'Memorial',
         'Se radican solicitud(es) de control de garantías y pasan al despacho', False, ''),
        ('Auto fija fecha y hora de audiencia', 'Providencia (auto/sentencia)',
         'El despacho profiere auto que fija fecha y hora para la audiencia', True, 'Programada'),
        ('Audiencia de control de garantías / cierre', 'Oficiosa',
         'Si la solicitud sigue vigente se realiza la audiencia; si terminó antes, registre su forma y fecha de salida sin crear audiencia',
         True, 'Realizada'),
    ],
)
_CARGOS = ['Juez', 'Secretario', 'Oficial Mayor', 'Escribiente', 'Citador']
_PERMISOS_ROL = {
    'Juez': ['audiencias.ver', 'estadistica.ver', 'estadistica.exportar'],
    'Secretario': ['audiencias.ver', 'audiencias.gestionar', 'estadistica.ver', 'estadistica.registrar',
                   'estadistica.exportar', 'config.personal'],
    'Escribiente': ['audiencias.ver', 'audiencias.gestionar', 'estadistica.ver'],
    'Consulta': ['audiencias.ver', 'estadistica.ver'],
}


def _datos() -> None:
    con = op.get_bind()
    catalogos = sa.table('catalogos', sa.column('tipo'), sa.column('valor'), sa.column('orden'))
    rutas = sa.table('rutas', sa.column('id'), sa.column('nombre'), sa.column('descripcion'), sa.column('orden'))
    pasos = sa.table('ruta_pasos', sa.column('ruta_id'), sa.column('orden'), sa.column('nombre'), sa.column('materia'),
                     sa.column('origen'), sa.column('termino'), sa.column('descripcion'), sa.column('es_audiencia'),
                     sa.column('aud_estado'))
    roles = sa.table('roles', sa.column('id'), sa.column('nombre'))
    rol_permisos = sa.table('rol_permisos', sa.column('rol_id'), sa.column('permiso'))

    def hay(sql, **kw) -> bool:
        return con.execute(sa.text(sql), kw).first() is not None

    if hay("SELECT 1 FROM config WHERE clave = 'semilla'"):
        def agregar(tipo, valor, al_inicio):
            if hay('SELECT 1 FROM catalogos WHERE tipo = :t AND valor = :v', t=tipo, v=valor):
                return
            fn = 'MIN(orden) - 1' if al_inicio else 'MAX(orden) + 1'
            orden = con.execute(sa.text(f'SELECT COALESCE({fn}, 0) FROM catalogos WHERE tipo = :t'), {'t': tipo}).scalar()
            con.execute(catalogos.insert().values(tipo=tipo, valor=valor, orden=orden))

        agregar('tipos_solicitud', 'Demanda', True)
        agregar('cuadernos', 'Incidente de desacato', False)
        if not hay("SELECT 1 FROM catalogos WHERE tipo = 'cargos'"):
            con.execute(catalogos.insert(), [{'tipo': 'cargos', 'valor': c, 'orden': i} for i, c in enumerate(_CARGOS)])
        rid, nombre, desc, lista = _GARANTIAS
        if not hay('SELECT 1 FROM rutas WHERE id = :id', id=rid):
            orden = con.execute(sa.text('SELECT COALESCE(MIN(orden) - 1, 0) FROM rutas')).scalar()
            con.execute(rutas.insert().values(id=rid, nombre=nombre, descripcion=desc, orden=orden))
            con.execute(pasos.insert(), [
                {'ruta_id': rid, 'orden': i, 'nombre': n, 'materia': 'Audiencia / diligencia', 'origen': o, 'termino': '',
                 'descripcion': d, 'es_audiencia': aud, 'aud_estado': est}
                for i, (n, o, d, aud, est) in enumerate(lista)
            ])

    for rol_id, rol in con.execute(sa.select(roles.c.id, roles.c.nombre)).all():
        for permiso in _PERMISOS_ROL.get(rol, []):
            if not hay('SELECT 1 FROM rol_permisos WHERE rol_id = :r AND permiso = :p', r=rol_id, p=permiso):
                con.execute(rol_permisos.insert().values(rol_id=rol_id, permiso=permiso))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('stat_eventos')
    op.drop_table('proceso_solicitudes_penales')
    op.drop_table('personal')
    op.drop_column('ruta_pasos', 'aud_estado')
    op.drop_column('ruta_pasos', 'es_audiencia')
    op.drop_column('procesos', 'cuadernos')
    op.drop_column('procesos', 'cuaderno_inicial')
    op.drop_column('procesos', 'des_consulta')
    op.drop_column('procesos', 'des_apertura')
    op.drop_column('procesos', 'des_req')
    op.drop_column('procesos', 'des_tutela')
    op.drop_column('procesos', 'medida_tutela')
    op.drop_column('procesos', 'decision_2da')
    op.drop_column('procesos', 'fecha_impugnacion')
    op.drop_column('procesos', 'impugnacion')
    op.drop_column('procesos', 'delitos_adicionales')
    op.drop_column('procesos', 'solicitud_penal')
    op.drop_column('procesos', 'noticia_criminal')
    op.drop_column('procesos', 'fecha_tramite_posterior')
    op.drop_column('procesos', 'tramite_posterior')
    op.drop_column('procesos', 'forma_salida')
    op.drop_column('procesos', 'fecha_archivo')
    op.drop_column('procesos', 'fecha_terminacion')
    op.drop_column('procesos', 'tipo_entrada')
    op.drop_column('procesos', 'via')
    op.drop_column('procesos', 'tipo_sierju')
    op.drop_column('actuaciones', 'ejec_dias')
    op.drop_column('actuaciones', 'notif_forma')
    op.drop_column('actuaciones', 'notif_fecha')
    op.drop_column('actuaciones', 'amparo_pobreza_concedido')
    op.drop_column('actuaciones', 'remate_realizado')
    op.drop_column('actuaciones', 'rec_impug_fecha')
    op.drop_column('actuaciones', 'rec_impug_result')
    op.drop_column('actuaciones', 'rec_impug')
    op.drop_column('actuaciones', 'superior_fecha')
    op.drop_column('actuaciones', 'superior_resultado')
    op.drop_column('actuaciones', 'rec_traslado')
    op.drop_column('actuaciones', 'recurso_objeto')
    op.drop_column('actuaciones', 'recurso_fecha')
    op.drop_column('actuaciones', 'recurso_tipo')
    op.drop_column('actuaciones', 'cancelacion_de')
    op.drop_column('actuaciones', 'aud_inmediata')
    op.drop_column('actuaciones', 'aud_causa')
    op.drop_column('actuaciones', 'aud_tipo')
    op.drop_column('actuaciones', 'aud_estado')
    op.drop_column('actuaciones', 'aud_hora')
    op.drop_column('actuaciones', 'aud_fecha')
    op.drop_column('actuaciones', 'es_audiencia')
    op.drop_column('actuaciones', 'entrada_stat')
    op.drop_column('actuaciones', 'salida_stat')
    op.drop_column('actuaciones', 'modo_cierre')
    op.drop_column('actuaciones', 'tipo_providencia')
    op.drop_column('actuaciones', 'asignado_a')
    op.drop_column('actuaciones', 'tp_tipo')
